spring.application.name=todolist
${jwt.secret}=fcf58d2eecc484261e24285083a2e84ef8fe8fb821687038b0db83abae256b56
spring.datasource.url=jdbc:postgresql://localhost:5432/tododb
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
